[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
    "flask>=3.0.0",
    "mistralai>=1.8.2",
    "pip>=25.1.1",
    "werkzeug>=3.1.3",
]
